// web/components/AppCard.tsx
import Image from 'next/image';
import Link from 'next/link';

import type { SnapshotAppIndexItem } from '@/lib/apps';

import { RiskPill } from './RiskPill';

interface AppCardProps {
  app: SnapshotAppIndexItem;
  compact?: boolean;
}

function AppIcon({ app }: { app: SnapshotAppIndexItem }): JSX.Element {
  if (app.iconUrl) {
    return (
      <Image
        src={app.iconUrl}
        alt={`${app.name} icon`}
        width={48}
        height={48}
        className="h-12 w-12 rounded-xl object-cover"
      />
    );
  }

  return (
    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-200 text-sm font-semibold text-slate-700">
      {app.name.slice(0, 1).toUpperCase()}
    </div>
  );
}

export function AppCard({ app, compact = false }: AppCardProps): JSX.Element {
  return (
    <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          <AppIcon app={app} />
          <div>
            <h3 className="text-base font-semibold text-slate-900">{app.name}</h3>
            <p className="text-xs text-slate-500">
              {app.category ?? 'Uncategorized'} {app.developer ? `· ${app.developer}` : ''}
            </p>
          </div>
        </div>
        <RiskPill level={app.riskLevel} />
      </div>

      <p className={`mt-3 text-sm text-slate-700 ${compact ? 'line-clamp-2' : ''}`}>{app.oneLineSummary}</p>

      <div className="mt-4 flex items-center justify-between">
        <p className="text-xs text-slate-500">Risk Score {app.riskScore}/100</p>
        <Link href={`/apps/${app.slug || app.id}`} className="text-sm font-medium text-slate-900 underline-offset-2 hover:underline">
          View detail
        </Link>
      </div>
    </article>
  );
}

// frontend/src/components/app/AppCard.vue
<script setup lang="ts">
import RiskBadge from '@/components/ui/RiskBadge.vue'
import { useSiteRuntimeSettings } from '@/composables/useSiteRuntimeSettings'

defineProps<{ app: any }>()
const { settings } = useSiteRuntimeSettings()
</script>

<template>
  <router-link :to="`/apps/${app.slug}`" class="panel block min-w-0 max-w-full overflow-hidden p-4 hover:border-signal">
    <div class="mb-3 flex items-start justify-between gap-4">
      <div class="min-w-0 flex-1">
        <div class="flex items-start gap-3">
          <div
            v-if="settings.showAppIcon"
            class="mt-0.5 h-11 w-11 shrink-0 overflow-hidden rounded-xl border border-charcoal bg-carbon"
          >
            <img
              v-if="app.iconUrl"
              :src="app.iconUrl"
              :alt="`${app.name} 图标`"
              class="h-full w-full object-cover"
              loading="lazy"
              referrerpolicy="no-referrer"
            >
            <div v-else class="flex h-full w-full items-center justify-center text-xs text-slate">
              App
            </div>
          </div>

          <div class="min-w-0">
            <div class="truncate text-lg font-semibold">{{ app.name }}</div>
            <div class="mt-1 flex w-full min-w-0 items-center gap-1 overflow-hidden text-sm text-slate">
              <span class="max-w-[42%] min-w-0 truncate" :title="app.category || '未分类'">
                {{ app.category || '未分类' }}
              </span>
              <span class="shrink-0">·</span>
              <span class="flex-1 min-w-0 truncate whitespace-nowrap" :title="app.developer || '未知开发商'">
                {{ app.developer || '未知开发商' }}
              </span>
            </div>
          </div>
        </div>
      </div>
      <RiskBadge :level="app.riskLevel" />
    </div>
    <p class="line-clamp-2 text-sm text-parchment">{{ app.oneLiner || app.plainSummary || '暂无摘要' }}</p>
    <div class="mt-4 text-xs text-slate">更新于 {{ app.updatedAtLabel || app.updatedAt }}</div>
  </router-link>
</template>
